include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --- 활성화 추천 규칙 ---
    avoid_print: true
    prefer_const_constructors: true
    always_specify_types: true

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'lib/generated_plugin_registrant.dart'

  errors:
    avoid_print: error